// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: ad.proto

package go_micro_service_ad

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Ad service

func NewAdEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Ad service

type AdService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type adService struct {
	c    client.Client
	name string
}

func NewAdService(name string, c client.Client) AdService {
	return &adService{
		c:    c,
		name: name,
	}
}

func (c *adService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Ad.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ad service

type AdHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterAdHandler(s server.Server, hdlr AdHandler, opts ...server.HandlerOption) error {
	type ad interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Ad struct {
		ad
	}
	h := &adHandler{hdlr}
	return s.Handle(s.NewHandler(&Ad{h}, opts...))
}

type adHandler struct {
	AdHandler
}

func (h *adHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AdHandler.Call(ctx, in, out)
}
