// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/answer/answer.proto

package go_micro_service_answer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Answer service

type AnswerService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Answer_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Answer_PingPongService, error)
}

type answerService struct {
	c    client.Client
	name string
}

func NewAnswerService(name string, c client.Client) AnswerService {
	return &answerService{
		c:    c,
		name: name,
	}
}

func (c *answerService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Answer.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *answerService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Answer_StreamService, error) {
	req := c.c.NewRequest(c.name, "Answer.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &answerServiceStream{stream}, nil
}

type Answer_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type answerServiceStream struct {
	stream client.Stream
}

func (x *answerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *answerServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *answerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *answerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *answerServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *answerService) PingPong(ctx context.Context, opts ...client.CallOption) (Answer_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Answer.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &answerServicePingPong{stream}, nil
}

type Answer_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type answerServicePingPong struct {
	stream client.Stream
}

func (x *answerServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *answerServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *answerServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *answerServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *answerServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *answerServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Answer service

type AnswerHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Answer_StreamStream) error
	PingPong(context.Context, Answer_PingPongStream) error
}

func RegisterAnswerHandler(s server.Server, hdlr AnswerHandler, opts ...server.HandlerOption) error {
	type answer interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Answer struct {
		answer
	}
	h := &answerHandler{hdlr}
	return s.Handle(s.NewHandler(&Answer{h}, opts...))
}

type answerHandler struct {
	AnswerHandler
}

func (h *answerHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AnswerHandler.Call(ctx, in, out)
}

func (h *answerHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AnswerHandler.Stream(ctx, m, &answerStreamStream{stream})
}

type Answer_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type answerStreamStream struct {
	stream server.Stream
}

func (x *answerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *answerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *answerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *answerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *answerStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *answerHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AnswerHandler.PingPong(ctx, &answerPingPongStream{stream})
}

type Answer_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type answerPingPongStream struct {
	stream server.Stream
}

func (x *answerPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *answerPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *answerPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *answerPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *answerPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *answerPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
