// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/split/split.proto

package go_micro_service_split

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Split service

type SplitService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Split_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Split_PingPongService, error)
}

type splitService struct {
	c    client.Client
	name string
}

func NewSplitService(name string, c client.Client) SplitService {
	return &splitService{
		c:    c,
		name: name,
	}
}

func (c *splitService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Split.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Split_StreamService, error) {
	req := c.c.NewRequest(c.name, "Split.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &splitServiceStream{stream}, nil
}

type Split_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type splitServiceStream struct {
	stream client.Stream
}

func (x *splitServiceStream) Close() error {
	return x.stream.Close()
}

func (x *splitServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *splitServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *splitServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *splitServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *splitService) PingPong(ctx context.Context, opts ...client.CallOption) (Split_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Split.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &splitServicePingPong{stream}, nil
}

type Split_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type splitServicePingPong struct {
	stream client.Stream
}

func (x *splitServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *splitServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *splitServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *splitServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *splitServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *splitServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Split service

type SplitHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Split_StreamStream) error
	PingPong(context.Context, Split_PingPongStream) error
}

func RegisterSplitHandler(s server.Server, hdlr SplitHandler, opts ...server.HandlerOption) error {
	type split interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Split struct {
		split
	}
	h := &splitHandler{hdlr}
	return s.Handle(s.NewHandler(&Split{h}, opts...))
}

type splitHandler struct {
	SplitHandler
}

func (h *splitHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SplitHandler.Call(ctx, in, out)
}

func (h *splitHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SplitHandler.Stream(ctx, m, &splitStreamStream{stream})
}

type Split_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type splitStreamStream struct {
	stream server.Stream
}

func (x *splitStreamStream) Close() error {
	return x.stream.Close()
}

func (x *splitStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *splitStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *splitStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *splitStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *splitHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SplitHandler.PingPong(ctx, &splitPingPongStream{stream})
}

type Split_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type splitPingPongStream struct {
	stream server.Stream
}

func (x *splitPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *splitPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *splitPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *splitPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *splitPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *splitPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
