// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sms/sms.proto

package go_micro_service_sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Sms service

type SmsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sms_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Sms_PingPongService, error)
}

type smsService struct {
	c    client.Client
	name string
}

func NewSmsService(name string, c client.Client) SmsService {
	return &smsService{
		c:    c,
		name: name,
	}
}

func (c *smsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Sms.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sms_StreamService, error) {
	req := c.c.NewRequest(c.name, "Sms.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &smsServiceStream{stream}, nil
}

type Sms_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type smsServiceStream struct {
	stream client.Stream
}

func (x *smsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *smsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smsService) PingPong(ctx context.Context, opts ...client.CallOption) (Sms_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Sms.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &smsServicePingPong{stream}, nil
}

type Sms_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type smsServicePingPong struct {
	stream client.Stream
}

func (x *smsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *smsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *smsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *smsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sms service

type SmsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Sms_StreamStream) error
	PingPong(context.Context, Sms_PingPongStream) error
}

func RegisterSmsHandler(s server.Server, hdlr SmsHandler, opts ...server.HandlerOption) error {
	type sms interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Sms struct {
		sms
	}
	h := &smsHandler{hdlr}
	return s.Handle(s.NewHandler(&Sms{h}, opts...))
}

type smsHandler struct {
	SmsHandler
}

func (h *smsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SmsHandler.Call(ctx, in, out)
}

func (h *smsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SmsHandler.Stream(ctx, m, &smsStreamStream{stream})
}

type Sms_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type smsStreamStream struct {
	stream server.Stream
}

func (x *smsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *smsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *smsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SmsHandler.PingPong(ctx, &smsPingPongStream{stream})
}

type Sms_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type smsPingPongStream struct {
	stream server.Stream
}

func (x *smsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *smsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *smsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
