// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/recom/recom.proto

package go_micro_service_recom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Recom service

type RecomService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Recom_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Recom_PingPongService, error)
}

type recomService struct {
	c    client.Client
	name string
}

func NewRecomService(name string, c client.Client) RecomService {
	return &recomService{
		c:    c,
		name: name,
	}
}

func (c *recomService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Recom.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recomService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Recom_StreamService, error) {
	req := c.c.NewRequest(c.name, "Recom.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &recomServiceStream{stream}, nil
}

type Recom_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type recomServiceStream struct {
	stream client.Stream
}

func (x *recomServiceStream) Close() error {
	return x.stream.Close()
}

func (x *recomServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *recomServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *recomServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *recomServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recomService) PingPong(ctx context.Context, opts ...client.CallOption) (Recom_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Recom.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &recomServicePingPong{stream}, nil
}

type Recom_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type recomServicePingPong struct {
	stream client.Stream
}

func (x *recomServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *recomServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *recomServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *recomServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *recomServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *recomServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Recom service

type RecomHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Recom_StreamStream) error
	PingPong(context.Context, Recom_PingPongStream) error
}

func RegisterRecomHandler(s server.Server, hdlr RecomHandler, opts ...server.HandlerOption) error {
	type recom interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Recom struct {
		recom
	}
	h := &recomHandler{hdlr}
	return s.Handle(s.NewHandler(&Recom{h}, opts...))
}

type recomHandler struct {
	RecomHandler
}

func (h *recomHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.RecomHandler.Call(ctx, in, out)
}

func (h *recomHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.RecomHandler.Stream(ctx, m, &recomStreamStream{stream})
}

type Recom_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type recomStreamStream struct {
	stream server.Stream
}

func (x *recomStreamStream) Close() error {
	return x.stream.Close()
}

func (x *recomStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *recomStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *recomStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *recomStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *recomHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.RecomHandler.PingPong(ctx, &recomPingPongStream{stream})
}

type Recom_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type recomPingPongStream struct {
	stream server.Stream
}

func (x *recomPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *recomPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *recomPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *recomPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *recomPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *recomPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
