// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/senword/senword.proto

package go_micro_service_senword

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Senword service

type SenwordService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Senword_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Senword_PingPongService, error)
}

type senwordService struct {
	c    client.Client
	name string
}

func NewSenwordService(name string, c client.Client) SenwordService {
	return &senwordService{
		c:    c,
		name: name,
	}
}

func (c *senwordService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Senword.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senwordService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Senword_StreamService, error) {
	req := c.c.NewRequest(c.name, "Senword.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &senwordServiceStream{stream}, nil
}

type Senword_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type senwordServiceStream struct {
	stream client.Stream
}

func (x *senwordServiceStream) Close() error {
	return x.stream.Close()
}

func (x *senwordServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *senwordServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *senwordServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *senwordServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *senwordService) PingPong(ctx context.Context, opts ...client.CallOption) (Senword_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Senword.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &senwordServicePingPong{stream}, nil
}

type Senword_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type senwordServicePingPong struct {
	stream client.Stream
}

func (x *senwordServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *senwordServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *senwordServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *senwordServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *senwordServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *senwordServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Senword service

type SenwordHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Senword_StreamStream) error
	PingPong(context.Context, Senword_PingPongStream) error
}

func RegisterSenwordHandler(s server.Server, hdlr SenwordHandler, opts ...server.HandlerOption) error {
	type senword interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Senword struct {
		senword
	}
	h := &senwordHandler{hdlr}
	return s.Handle(s.NewHandler(&Senword{h}, opts...))
}

type senwordHandler struct {
	SenwordHandler
}

func (h *senwordHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SenwordHandler.Call(ctx, in, out)
}

func (h *senwordHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SenwordHandler.Stream(ctx, m, &senwordStreamStream{stream})
}

type Senword_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type senwordStreamStream struct {
	stream server.Stream
}

func (x *senwordStreamStream) Close() error {
	return x.stream.Close()
}

func (x *senwordStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *senwordStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *senwordStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *senwordStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *senwordHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SenwordHandler.PingPong(ctx, &senwordPingPongStream{stream})
}

type Senword_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type senwordPingPongStream struct {
	stream server.Stream
}

func (x *senwordPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *senwordPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *senwordPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *senwordPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *senwordPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *senwordPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
